version: "3"



services:
#  postgres:
  postgres:
    container_name: postgres_db
    image: postgres:9.6
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db:/var/lib/postgresql/config
      - ./db:/var/log/postgresql
#    restart: always
#    tty: true
